### ISSUE TITLE
The web link to Cornell at the beginning of your book is broken.

### ISSUE THREAD

**Issue by chaikens** [dkmiller/algebraic-groups#1]

**Comment by dkmiller** [comment]
Just updated the link to https://github.com/dkmiller/algebraic-groups/releases/download/refs%2Fheads%2Fmaster/algebraic-groups.pdf .

@chaikens , can you check the PDF there and make sure the link works?

**Comment by chaikens** [comment]
Hi Daniel, The new link works.  I'll update in a Wikipedia article where I used it in place of broken link to similar material.  It's a very helpful writup on the subject.  Thanks.
